# Project information
site_name: A Monitoria
site_description: Artefatos de Desenho e Arquitetura de Software, 2019.2
site_author: Grupo 05 (Brainly++)
site_url: https://2019-2-arquitetura-desenho.github.io/wiki/

# Repository
repo_name: A Monitoria
repo_url: https://github.com/2019-2-arquitetura-desenho/wiki

# Copyright
copyright: 'Copyright &copy; 2019 A Monitoria'

# Theme settings
theme:
  logo: assets/img/logo/logo_icon.png
  # favicon: 
  font:
    text: Roboto
    code: Roboto Mono
  feature:
    tabs: true
  language: 'pt'
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'purple'

# Content Menu
pages:
  - Início: index.md
nav:
  - Dinâmicas e Seminários:
    - Dinâmica e Seminário I:
      - Design Sprint: dinamica_seminario_I/design_sprint.md
      - Definição do tema:
        - 5W2H: dinamica_seminario_I/definicao_tema/5W2H.md
        - Rich Picture: dinamica_seminario_I/definicao_tema/rich_picture.md
        - Ishikawa: dinamica_seminario_I/definicao_tema/ishikawa.md
  - Iniciativas Extras:
    - Extensões: samples.md

# Style
extra_css:
  - assets/style/extra.css

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
